---
title: Hallm's Thoughts
timezone: America/Chicago
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Random thoughts and links from the mind of hallm

'
baseurl: 
url: http://hallm.siteleaf.net
twitter_username: hallm
markdown: kramdown

theme: jekyll-theme-tactile